#!/bin/bash
set -euo pipefail
STAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${STAGE_DIR}/common.sh"

# Part 2: run the software TPMs as supervised systemd units.
#
# The guide starts a single swtpm with nohup. Two changes here:
#   1. systemd instead of nohup, so the TPM survives a reboot and its output
#      lands in the journal rather than a stray log file.
#   2. two instances, `device` and `attacker`. The Part 8.1 stolen-key demo
#      needs a second TPM with a different storage seed; running both at once
#      on separate ports means the demo just re-points the TCTI instead of
#      killing and restarting the only TPM in the lab.

log_step "Part 2: start the software TPMs (swtpm@device, swtpm@attacker)"

DEVICE_PORT="${1:-${TPM_PORT}}"
ATTACKER_PORT="${2:-${ATTACKER_TPM_PORT}}"

# TPM state lives under the lab user's home, not /var/lib.
#
# Ubuntu ships an enforcing AppArmor profile for swtpm (/etc/apparmor.d/
# usr.bin.swtpm) that permits state only under `owner @{HOME}/**` and
# `owner /var/lib/swtpm/**`. A path like /var/lib/swtpm-lab is denied when swtpm
# creates its .lock file, and the daemon exits with a misleading
# "Could not open lockfile: Permission denied" despite the directory being owned
# by the right user.
#
# Keeping state under $LAB_DIR satisfies the existing policy, so the lab needs
# no `aa-complain` and AppArmor stays in enforce mode. It also means `task reset`
# clears TPM state along with the rest of the lab tree.
STATE_ROOT="${LAB_DIR}/tpmstate"
ENV_DIR="/etc/swtpm-lab"
UNIT_PATH="/etc/systemd/system/swtpm@.service"

INSTANCES=(device attacker)
declare -A INSTANCE_PORT=(
  [device]="${DEVICE_PORT}"
  [attacker]="${ATTACKER_PORT}"
)

require_cmd swtpm swtpm_setup systemctl || die "run 'task provision' first"
# as_lab_user sources this file, so every later verification depends on it.
[[ -f "${LAB_DIR}/env.sh" ]] || die "${LAB_DIR}/env.sh is missing — run 'task provision' first"

for inst in "${INSTANCES[@]}"; do
  port="${INSTANCE_PORT[${inst}]}"
  [[ "${port}" =~ ^[0-9]+$ ]] || die "invalid port '${port}' for instance '${inst}'"
done

# --- state directories -------------------------------------------------------

# 0700 and owned by the lab user: swtpm runs as that user, and the state file
# holds the storage seed that makes a TPM-wrapped key blob non-portable. Not
# lab_mkdir, which is deliberately 0755.
install -d -o "${LAB_USER}" -g "${LAB_USER}" -m 0755 "${STATE_ROOT}"
for inst in "${INSTANCES[@]}"; do
  install -d -o "${LAB_USER}" -g "${LAB_USER}" -m 0700 "${STATE_ROOT}/${inst}"
done
log_ok "state directories under ${STATE_ROOT} (0700, ${LAB_USER})"

# --- per-instance port files -------------------------------------------------

# A templated unit cannot vary its ports by itself, so each instance gets an
# EnvironmentFile that systemd resolves from %i. The control channel sits one
# port above the command channel, matching the guide's 2321/2322 pairing.
install -d -m 0755 "${ENV_DIR}"
declare -A NEEDS_RESTART=()
for inst in "${INSTANCES[@]}"; do
  port="${INSTANCE_PORT[${inst}]}"
  ctrl_port=$(( port + 1 ))
  if write_if_changed "${ENV_DIR}/${inst}.env" <<EOF
# Ports for swtpm@${inst}. Written by scripts/10_tpm_unit.sh.
SWTPM_PORT=${port}
SWTPM_CTRL_PORT=${ctrl_port}
EOF
  then
    log_info "Wrote ${ENV_DIR}/${inst}.env (server ${port}, ctrl ${ctrl_port})"
    NEEDS_RESTART[${inst}]=1
  else
    log_detected "unchanged ${ENV_DIR}/${inst}.env" "instance '${inst}' keeps port ${port}"
  fi
done

# --- the templated unit ------------------------------------------------------

# Authoritative copy of the unit. templates/swtpm.service.tpl is the readable
# reference of exactly this content and must be kept in sync — templates live
# on the host and are never transferred into the VM, so the unit has to be
# written inline here.
#
# \${SWTPM_PORT} / \${SWTPM_CTRL_PORT} are escaped so systemd expands them from
# the EnvironmentFile; %i is systemd's instance-name specifier.
unit_changed=0
if write_if_changed "${UNIT_PATH}" <<EOF
# Software TPM 2.0 (%i). Generated by scripts/10_tpm_unit.sh.
[Unit]
Description=Software TPM 2.0 (%i)
Documentation=man:swtpm(8)
After=network.target

[Service]
Type=simple
User=${LAB_USER}
Group=${LAB_USER}
EnvironmentFile=${ENV_DIR}/%i.env
ExecStart=/usr/bin/swtpm socket --tpm2 --tpmstate dir=${STATE_ROOT}/%i --server type=tcp,port=\${SWTPM_PORT} --ctrl type=tcp,port=\${SWTPM_CTRL_PORT} --flags not-need-init,startup-clear
Restart=on-failure
RestartSec=1

[Install]
WantedBy=multi-user.target
EOF
then
  unit_changed=1
  log_info "Wrote ${UNIT_PATH}"
else
  log_detected "unchanged ${UNIT_PATH}" "no systemd reload needed for the unit"
fi

# --- one-time TPM manufacturing ---------------------------------------------

# Does a fresh state directory need swtpm_setup before the socket will start?
#
# Reasoning: `--flags not-need-init,startup-clear` is about the *runtime*
# handshake — it tells swtpm not to wait for an INIT on the control channel and
# to issue TPM2_Startup(CLEAR) itself. It says nothing about manufacturing. On
# an empty state directory libtpms builds default blank state and swtpm
# persists it, so the socket does start and tpm2_getrandom / key creation work.
# What is missing without swtpm_setup is the endorsement key and the EK and
# platform certificates in NVRAM — needed for attestation-based enrolment, not
# for this lab, which only creates and uses an ordinary TPM-resident key.
#
# So swtpm_setup is very likely unnecessary. It is run anyway because it is the
# safe superset: it costs one command on first provision, it makes the lab TPM
# look like a real manufactured one, and it leaves the door open for the Part
# 9.3 / EK-attestation stretch goals. It is best-effort — a failure here is
# logged and the socket is started regardless, since the socket does not depend
# on it. UNCERTAINTY: confirm on the first real run that swtpm_setup succeeds
# on 24.04 arm64 (it shells out to swtpm_localca, which wants certtool from
# gnutls-bin); if it warns, check that the units still come up, which they
# should.
for inst in "${INSTANCES[@]}"; do
  state_dir="${STATE_ROOT}/${inst}"
  marker="${state_dir}/.lab-setup-done"
  # Skip if the state was already manufactured, if swtpm has persisted state of
  # its own, or if the instance is already running — never re-manufacture under
  # a live TPM, which would invalidate every key blob already wrapped to it.
  if [[ -e "${marker}" || -e "${state_dir}/tpm2-00.permall" ]] \
    || systemctl is-active --quiet "swtpm@${inst}"; then
    log_detected "existing TPM state in ${state_dir}" "skipping swtpm_setup for '${inst}'"
    continue
  fi
  log_info "Manufacturing TPM state for '${inst}' (first run only, takes a few seconds)..."
  # Run as the lab user: swtpm runs as that user against a 0700 directory, so
  # root-owned state files here would make the service fail to read its own state.
  if as_lab_user swtpm_setup --tpm2 --tpmstate "${state_dir}" \
      --createek --create-ek-cert --create-platform-cert --lock-nvram; then
    touch "${marker}"
    chown "${LAB_USER}:${LAB_USER}" "${marker}"
    log_ok "swtpm_setup completed for '${inst}'"
  else
    log_warn "swtpm_setup failed for '${inst}' — continuing, because --flags not-need-init,startup-clear lets swtpm create default state on its own. Only EK/platform certificates are missing, which this lab does not use."
  fi
  NEEDS_RESTART[${inst}]=1
done

# --- start ------------------------------------------------------------------

if (( unit_changed == 1 )); then
  log_info "Reloading systemd (unit changed)..."
  systemctl daemon-reload
fi

log_info "Enabling and starting swtpm@device and swtpm@attacker..."
systemctl enable --now swtpm@device swtpm@attacker

# `enable --now` is a no-op for an already-running instance, so anything whose
# unit or port file changed needs an explicit restart to pick the change up.
for inst in "${INSTANCES[@]}"; do
  if (( unit_changed == 1 )) || [[ -n "${NEEDS_RESTART[${inst}]:-}" ]]; then
    log_info "Restarting swtpm@${inst} to pick up the new configuration..."
    systemctl restart "swtpm@${inst}"
  fi
done

# --- verify ------------------------------------------------------------------

log_step "Verify Part 2"

# AppArmor confines swtpm on Ubuntu. State under $LAB_DIR is inside the
# profile's `owner @{HOME}/**` rule so the default policy already permits it,
# but a customised STATE_ROOT or a tightened local profile can still trip a
# denial. That denial never appears in the unit's own journal — only in the
# kernel ring buffer — so check for it explicitly and surface the remedy.
report_start_failure() {
  local unit="$1"
  if journalctl -k --no-pager -n 500 2>/dev/null | grep -qiE 'apparmor.*swtpm' \
    || dmesg 2>/dev/null | grep -qiE 'apparmor.*swtpm'; then
    log_error "AppArmor denied swtpm — remedy: sudo aa-complain /usr/bin/swtpm, then re-run 'task tpm'"
  fi
  log_error "inspect with: journalctl -u ${unit} --no-pager -n 50"
}

for inst in "${INSTANCES[@]}"; do
  if ! wait_for_unit "swtpm@${inst}" 30; then
    report_start_failure "swtpm@${inst}"
    die "swtpm@${inst} did not become active"
  fi
done

# The unit being active only means the process is alive. This proves the TPM
# answers commands over the TCTI the lab environment actually uses.
wait_for "device TPM responding" 30 as_lab_user tpm2_getrandom 8 --hex \
  || die "the device TPM did not answer on port ${DEVICE_PORT} — check 'journalctl -u swtpm@device'"

# Same check against the attacker TPM, which Part 8.1 depends on. env.sh writes
# its TCTI with a :- default, so an inline override wins.
wait_for "attacker TPM responding" 30 \
  as_lab_user env "TPM2TOOLS_TCTI=swtpm:port=${ATTACKER_PORT}" tpm2_getrandom 8 --hex \
  || die "the attacker TPM did not answer on port ${ATTACKER_PORT} — check 'journalctl -u swtpm@attacker'"

log_info "tpm2_getrandom 8 --hex:"
log_detail "  $(as_lab_user tpm2_getrandom 8 --hex)"

log_info "TPM2_PT_MANUFACTURER:"
as_lab_user tpm2_getcap properties-fixed | grep -A2 TPM2_PT_MANUFACTURER | sed 's/^/  /' \
  || log_warn "TPM2_PT_MANUFACTURER not found in tpm2_getcap properties-fixed"

log_info "openssl providers:"
as_lab_user openssl list -providers -provider tpm2 -provider default | sed 's/^/  /' \
  || log_warn "the tpm2 OpenSSL provider did not load — check that tpm2-openssl is installed"

log_ok "Part 2 complete: device TPM on ${DEVICE_PORT}, attacker TPM on ${ATTACKER_PORT} — next: task vault"
