#!/bin/bash
set -euo pipefail
STAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${STAGE_DIR}/common.sh"

# Part 2: run the software TPMs as supervised systemd units.
#
# Two instances, `device` and `attacker`. The Part 8 demos need a second TPM
# with a different storage seed; running both permanently means a demo just
# points at a different socket instead of killing and restarting the only TPM
# in the lab.
#
# Each TPM is served on a unix socket inside its own state directory. That one
# path is shared by everything that talks to the TPM — tpm2-tools through the
# swtpm TCTI, and the Vault CLI through -tpm-device-path — which is exactly the
# shape of a real machine, where the path is /dev/tpmrm0 instead.

log_step "Part 2: start the software TPMs (swtpm@device, swtpm@attacker)"

STATE_ROOT="${TPM_STATE_ROOT}"
UNIT_PATH="/etc/systemd/system/swtpm@.service"
# Per-instance port files from the earlier TCP design. Removed if present.
LEGACY_ENV_DIR="/etc/swtpm-lab"

INSTANCES=(device attacker)
declare -A INSTANCE_SOCK=(
  [device]="${TPM_SOCK}"
  [attacker]="${ATTACKER_TPM_SOCK}"
)

require_cmd swtpm swtpm_setup systemctl || die "run 'task provision' first"
# as_lab_user sources this file, so every later verification depends on it.
[[ -f "${LAB_DIR}/env.sh" ]] || die "${LAB_DIR}/env.sh is missing — run 'task provision' first"

# --- state directories -------------------------------------------------------

# 0700 and owned by the lab user: swtpm runs as that user, and the state file
# holds the storage seed that makes a TPM-wrapped key blob non-portable. Not
# lab_mkdir, which is deliberately 0755.
#
# Ubuntu ships an enforcing AppArmor profile for swtpm (/etc/apparmor.d/
# usr.bin.swtpm) that permits state only under `owner @{HOME}/**` and
# `owner /var/lib/swtpm/**`. Keeping state (and the sockets) under $LAB_DIR
# satisfies that policy, so AppArmor stays in enforce mode.
install -d -o "${LAB_USER}" -g "${LAB_USER}" -m 0755 "${STATE_ROOT}"
for inst in "${INSTANCES[@]}"; do
  install -d -o "${LAB_USER}" -g "${LAB_USER}" -m 0700 "${STATE_ROOT}/${inst}"
done
log_ok "state directories under ${STATE_ROOT} (0700, ${LAB_USER})"

if [[ -d "${LEGACY_ENV_DIR}" ]]; then
  log_detected "port files from the old TCP layout in ${LEGACY_ENV_DIR}" "removing them — the TPMs now serve unix sockets"
  rm -rf "${LEGACY_ENV_DIR}"
fi

# --- the templated unit ------------------------------------------------------

# Authoritative copy of the unit. templates/swtpm.service.tpl is the readable
# reference of exactly this content and must be kept in sync — templates live
# on the host and are never transferred into the VM, so the unit has to be
# written inline here.
#
# %i is systemd's instance-name specifier. The .ctrl socket is swtpm's control
# channel, used only by the swtpm TCTI. A stale socket left by an unclean stop
# would block the bind, hence the ExecStartPre.
unit_changed=0
if write_if_changed "${UNIT_PATH}" <<EOF
# Software TPM 2.0 (%i). Generated by scripts/10_tpm_unit.sh.
[Unit]
Description=Software TPM 2.0 (%i)
Documentation=man:swtpm(8)

[Service]
Type=simple
User=${LAB_USER}
Group=${LAB_USER}
ExecStartPre=/bin/rm -f ${STATE_ROOT}/%i/swtpm.sock ${STATE_ROOT}/%i/swtpm.sock.ctrl
ExecStart=/usr/bin/swtpm socket --tpm2 --tpmstate dir=${STATE_ROOT}/%i --server type=unixio,path=${STATE_ROOT}/%i/swtpm.sock --ctrl type=unixio,path=${STATE_ROOT}/%i/swtpm.sock.ctrl --flags not-need-init,startup-clear
Restart=on-failure
RestartSec=1

[Install]
WantedBy=multi-user.target
EOF
then
  unit_changed=1
  log_info "Wrote ${UNIT_PATH}"
else
  log_detected "unchanged ${UNIT_PATH}" "no systemd reload needed for the unit"
fi

# --- one-time TPM manufacturing ---------------------------------------------

# `--flags not-need-init,startup-clear` is about the runtime handshake: swtpm
# does not wait for an INIT on the control channel and issues
# TPM2_Startup(CLEAR) itself. On an empty state directory libtpms builds blank
# default state, so the socket would start without swtpm_setup — but the
# endorsement key would then be created lazily and without the EK certificate
# a manufactured TPM carries. swtpm_setup makes the lab TPM look like a real
# one, and it is the EK that Vault's identity/tpm registry is keyed on.
#
# It is best-effort: a failure here is logged and the socket is started
# regardless. Known failure modes on 24.04 arm64 (swtpm 0.7.3), both fixed:
#   1. "Could not create temporary directory for certs: Permission denied" —
#      the lab user inherited a root-owned TMPDIR. common.sh chowns it.
#   2. "swtpm_localca: Need read/write rights on statedir
#      /var/lib/swtpm-localca" — the packaged local CA is owned by the `swtpm`
#      system user. --create-config-files below writes a per-user config whose
#      local CA lives under ~/.config/var/lib/swtpm-localca.
log_info "Ensuring ${LAB_USER} has a per-user swtpm_setup config (~/.config)..."
if as_lab_user swtpm_setup --create-config-files skip-if-exist; then
  log_ok "swtpm_setup per-user config present for ${LAB_USER}"
else
  log_warn "could not create per-user swtpm_setup config — manufacturing below may fall back to the packaged local CA and fail; the socket does not depend on it"
fi

declare -A NEEDS_RESTART=()
for inst in "${INSTANCES[@]}"; do
  state_dir="${STATE_ROOT}/${inst}"
  marker="${state_dir}/.lab-setup-done"
  # Skip if the state was already manufactured, if swtpm has persisted state of
  # its own, or if the instance is already running — never re-manufacture under
  # a live TPM, which would invalidate every key blob already wrapped to it.
  if [[ -e "${marker}" || -e "${state_dir}/tpm2-00.permall" ]] \
    || systemctl is-active --quiet "swtpm@${inst}"; then
    log_detected "existing TPM state in ${state_dir}" "skipping swtpm_setup for '${inst}'"
    continue
  fi
  log_info "Manufacturing TPM state for '${inst}' (first run only, takes a few seconds)..."
  # Run as the lab user: swtpm runs as that user against a 0700 directory, so
  # root-owned state files here would make the service fail to read its own state.
  if as_lab_user swtpm_setup --tpm2 --tpmstate "${state_dir}" \
      --createek --create-ek-cert --create-platform-cert --lock-nvram; then
    touch "${marker}"
    chown "${LAB_USER}:${LAB_USER}" "${marker}"
    log_ok "swtpm_setup completed for '${inst}'"
  else
    log_warn "swtpm_setup failed for '${inst}' — continuing, because --flags not-need-init,startup-clear lets swtpm create default state on its own. The EK is then created on first use, without an EK certificate; enrolment does not need the certificate."
  fi
  NEEDS_RESTART[${inst}]=1
done

# --- start ------------------------------------------------------------------

if (( unit_changed == 1 )); then
  log_info "Reloading systemd (unit changed)..."
  systemctl daemon-reload
fi

log_info "Enabling and starting swtpm@device and swtpm@attacker..."
systemctl enable --now swtpm@device swtpm@attacker

# `enable --now` is a no-op for an already-running instance, so anything whose
# unit changed needs an explicit restart to pick the change up.
for inst in "${INSTANCES[@]}"; do
  if (( unit_changed == 1 )) || [[ -n "${NEEDS_RESTART[${inst}]:-}" ]]; then
    log_info "Restarting swtpm@${inst} to pick up the new configuration..."
    systemctl restart "swtpm@${inst}"
  fi
done

# --- verify ------------------------------------------------------------------

log_step "Verify Part 2"

# AppArmor confines swtpm on Ubuntu. State under $LAB_DIR is inside the
# profile's `owner @{HOME}/**` rule so the default policy already permits it,
# but a customised STATE_ROOT or a tightened local profile can still trip a
# denial. That denial never appears in the unit's own journal — only in the
# kernel ring buffer — so check for it explicitly and surface the remedy.
report_start_failure() {
  local unit="$1"
  if journalctl -k --no-pager -n 500 2>/dev/null | grep -qiE 'apparmor.*swtpm' \
    || dmesg 2>/dev/null | grep -qiE 'apparmor.*swtpm'; then
    log_error "AppArmor denied swtpm — remedy: sudo aa-complain /usr/bin/swtpm, then re-run 'task tpm'"
  fi
  log_error "inspect with: journalctl -u ${unit} --no-pager -n 50"
}

for inst in "${INSTANCES[@]}"; do
  if ! wait_for_unit "swtpm@${inst}" 30; then
    report_start_failure "swtpm@${inst}"
    die "swtpm@${inst} did not become active"
  fi
done

# The unit being active only means the process is alive. This proves each TPM
# answers commands over the socket the lab environment actually uses. env.sh
# writes the TCTI with a :- default, so an inline override wins.
for inst in "${INSTANCES[@]}"; do
  sock="${INSTANCE_SOCK[${inst}]}"
  wait_for "${inst} TPM responding on ${sock}" 30 \
    as_lab_user env "TPM2TOOLS_TCTI=swtpm:path=${sock}" tpm2_getrandom 8 --hex \
    || die "the ${inst} TPM did not answer on ${sock} — check 'journalctl -u swtpm@${inst}'"
done

log_info "tpm2_getrandom 8 --hex (device TPM):"
log_detail "  $(as_lab_user tpm2_getrandom 8 --hex)"

log_info "TPM2_PT_MANUFACTURER:"
as_lab_user tpm2_getcap properties-fixed | grep -A2 TPM2_PT_MANUFACTURER | sed 's/^/  /' \
  || log_warn "TPM2_PT_MANUFACTURER not found in tpm2_getcap properties-fixed"

# The endorsement key is what Vault will register. Two TPMs, two EKs, two IDs:
# the contrast is what the Part 8 demos rest on.
if command -v vault >/dev/null 2>&1; then
  log_info "Endorsement key IDs, as the Vault CLI computes them (sha256 of the EK public key):"
  for inst in "${INSTANCES[@]}"; do
    sock="${INSTANCE_SOCK[${inst}]}"
    flush_tpm_contexts "${sock}"
    tpm_id="$(as_lab_user_allow_fail vault tpm ek -tpm-device-path="${sock}" -format=json 2>/dev/null \
      | jq -r '.tpm_id // empty' || true)"
    log_detail "  ${inst}: ${tpm_id:-(could not read the EK)}"
  done
fi

log_ok "Part 2 complete: device TPM at ${TPM_SOCK}, attacker TPM at ${ATTACKER_TPM_SOCK} — next: task vault"
