#!/bin/bash
set -euo pipefail
STAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${STAGE_DIR}/common.sh"

# Part 3: run the Vault dev server (TLS) as a supervised systemd unit.
#
# The guide backgrounds `vault server -dev` with nohup and sleeps. A unit gives
# the same server a journal, a restart policy, and a readiness signal the rest
# of the lab can wait on instead of guessing.

log_step "Part 3: start the Vault dev server (TLS)"

UNIT_PATH="/etc/systemd/system/vault-dev.service"

VAULT_BIN="/usr/local/bin/vault"
LICENCE_PATH="${VM_DIR}/vault.hclic"

require_cmd systemctl || die "systemctl not found"
[[ -x "${VAULT_BIN}" ]] || die "${VAULT_BIN} is missing — run 'task provision' first"
[[ -f "${VM_DIR}/env.sh" ]] || die "${VM_DIR}/env.sh is missing — run 'task provision' first"
[[ -s "${LICENCE_PATH}" ]] \
  || log_warn "no licence at ${LICENCE_PATH} — Vault Enterprise will refuse to start; copy it to .bin/vault.hclic on the host and re-run 'task provision'"

# The dev server writes its self-signed certificate material here on every
# start, so the directory must exist and be writable by the lab user.
lab_mkdir "${VM_DIR}" "${TLS_DIR}"

# The HashiCorp package ships its own vault.service for a production server.
# It would bind the same 127.0.0.1:8200 and fight this unit for the port.
if systemctl is-enabled --quiet vault.service 2>/dev/null \
  || systemctl is-active --quiet vault.service 2>/dev/null; then
  log_detected "the packaged vault.service running or enabled" "disabling it so it cannot contend for 127.0.0.1:8200"
  systemctl disable --now vault.service
fi

# --- the unit ---------------------------------------------------------------

# Authoritative copy of the unit. templates/vault-dev.service.tpl is the
# readable reference of exactly this content and must be kept in sync —
# templates live on the host and are never transferred into the VM, so the unit
# has to be written inline here.
#
# -dev-listen-address is deliberately omitted: it defaults to 127.0.0.1:8200,
# and -dev-tls issues the certificate for 127.0.0.1 only. Binding anywhere else
# would make every client fail certificate verification.
unit_changed=0
if write_if_changed "${UNIT_PATH}" <<EOF
# Vault dev server (TLS) for the TPM cert-auth lab.
# Generated by scripts/20_vault_unit.sh.
[Unit]
Description=Vault dev server (TLS) for the TPM cert-auth lab
Documentation=https://developer.hashicorp.com/vault/docs/commands/server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${VM_USER}
Group=${VM_USER}
WorkingDirectory=${VM_DIR}
Environment=VAULT_LICENSE_PATH=${LICENCE_PATH}
ExecStart=${VAULT_BIN} server -dev -dev-tls -dev-root-token-id=root -dev-tls-cert-dir=${TLS_DIR}
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF
then
  unit_changed=1
  log_info "Wrote ${UNIT_PATH}"
else
  log_detected "unchanged ${UNIT_PATH}" "no systemd reload needed"
fi

if (( unit_changed == 1 )); then
  log_info "Reloading systemd (unit changed)..."
  systemctl daemon-reload
fi

log_info "Enabling and starting vault-dev..."
systemctl enable --now vault-dev

# `enable --now` will not restart an already-running server, so a changed unit
# needs an explicit restart. This wipes dev-mode state — the caller is told below.
if (( unit_changed == 1 )); then
  log_info "Restarting vault-dev to pick up the new unit..."
  systemctl restart vault-dev
fi

# --- verify ------------------------------------------------------------------

log_step "Verify Part 3"

if ! wait_for_unit vault-dev 30; then
  die "vault-dev did not become active — inspect with: journalctl -u vault-dev --no-pager -n 50"
fi

# `vault status` is its own readiness probe: exit 0 unsealed, 2 sealed,
# non-zero while the listener is still coming up. No parsing needed.
wait_for "Vault to report unsealed" 60 as_lab_user vault status \
  || die "Vault never reported unsealed — inspect with: journalctl -u vault-dev --no-pager -n 50"

log_info "Contents of ${TLS_DIR} (expect vault-ca.pem, vault-cert.pem, vault-key.pem):"
ls -1 "${TLS_DIR}" | sed 's/^/  /'

for f in vault-ca.pem vault-cert.pem vault-key.pem; do
  [[ -s "${TLS_DIR}/${f}" ]] || log_warn "missing or empty: ${TLS_DIR}/${f}"
done

log_info "vault status (expect 'Sealed false' and 'Storage Type inmem'):"
as_lab_user vault status | sed 's/^/  /'

log_warn "Dev mode keeps everything in memory. Restarting vault-dev wipes the tpm auth mount and its CA, the TPM registry, the policies and the KV secret — run 'task config && task enrol' to rebuild them."
log_ok "Part 3 complete — next: task config"
